# Generated by Django 3.2.7 on 2021-09-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210928_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='img',
            new_name='image',
        ),
    ]
